### ISSUE TITLE
[BUG] prop table titles not changing in dark mode of displayCard

### ISSUE THREAD

**Issue by Ddupasquier** [Ddupasquier/mysvelte_ui#7]
**Describe the bug**
The title says it all. Simple fix.

**Expected behavior**
The titles should switch the white when the displayCard is in dark mode.

**Additional context**
This can be found in the ui_components/displayCard/displayPropsTable

**Comment by 1nayeeyan** [comment]
I'll take this on!

**Comment by Ddupasquier** [comment]
@1nayeeyan 
Sounds great!!! If you could make the PR to staging that would be great! I need to change the default branch from main once yo're done. Been forgetting to do that.

**Comment by 1nayeeyan** [comment]
Hey, was busy for a few days, and I want to finish this issue today. I figured the best way to test out changes was by creating my own svelte project, editing source code, then reloading the project to see changes. Is there another way to go about this?

**Comment by Ddupasquier** [comment]
@1nayeeyan 
I mean, you already have a fork of the project. So all you have to do is run your local server and you'll see the changes in your own browser. Once you've achieved the desired result, just open a pull request to staging.

**Comment by Ddupasquier** [comment]
I've taken it upon myself to fix this issue. Fixes will be available in next update.

**Comment by Ddupasquier** [comment]
https://github.com/Ddupasquier/mysvelte_ui/commit/8934a5e435912c7a5f4b4d51598be597d8bfd46f
